version: '3.8'

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # 現在のディレクトリをコンテナの/home/vscode/projectにマウント
      - .:/home/vscode/project
      # 設定ファイル用のマウント (必要に応じて追加)
      # - ./config:/config
      # - ./tools:/tools
      # tiniを使用して適切にプロセスを管理
    init: true
    # 環境変数の設定
    environment:
      - NODE_ENV=development
    # 明示的なコマンドで常駐させる
    command: [ "/bin/bash", "-c", "tail -f /dev/null" ]
